Repository homarr-labs/documentation, pull requests merged in 2025-03, with the labels that each got.

#211 docs(kubernetes): add kubernetes tool documentation
  docs/advanced/development/kubernetes.mdx
  docs/integrations/img/kubernetes/dashboard.jpeg
  docs/integrations/kubernetes.mdx
Labels: helm, kubernetes

#243 docs: document custom css
  docs/advanced/styling/img/custom-css-setting.png
  docs/advanced/styling/img/enter-board-settings.png
  docs/advanced/styling/img/widget-custom-classes.png
  docs/advanced/styling/index.mdx
Labels: documentation

#242 docs(widget): add stocks widget
  docs/widgets/stocks/img/screenshot.png
  docs/widgets/stocks/index.mdx
  versioned_docs/version-1.12.0/widgets/stocks/img/screenshot.png
  versioned_docs/version-1.12.0/widgets/stocks/index.mdx
Labels: documentation

#252 feat: overhaul start page
  package.json
  pnpm-lock.yaml
  src/components/pages/home/dataflow/dataflow.tsx
  src/components/pages/home/drag-and-drop/drag-and-drop-showcase.tsx
  src/components/pages/home/hero/hero-cards.tsx
  src/components/pages/home/hero/hero.tsx
  src/components/pages/home/hero/widgets/app-widget.tsx
  src/components/pages/home/hero/widgets/card.tsx
  src/components/pages/home/hero/widgets/clock-widget.tsx
  src/components/pages/home/hero/widgets/downloads-widget.tsx
  src/components/pages/home/hero/widgets/entity-state-widget.tsx
  src/components/pages/home/hero/widgets/stock-widget.tsx
  src/components/pages/home/hero/widgets/weather-widget.tsx
  src/components/pages/home/integrations/available-integrations.tsx
  src/components/pages/home/review-list/review-list.tsx
  src/constants/supported-integrations.tsx
  src/css/custom.css
  src/pages/index.module.css
  src/tools/math.ts
  tailwind.config.js
Labels: enhancement
